print("prima riga")
print("ciao","tutti")
print(7-8)
print(5+9)
print(4*6)
print(4%5)
print(7/8)
print(4//3)
print(4**7)
print(5.7+8)
print("ciao a tutti" + " a tutti")
print("primo " ,type(38))
print("secondo " ,type(38.9))
print("terzo " ,type("38"))
print("ciao sono francesco e ho "+ str(38))
print(8+int("8"))